Обновление панели с расписанием
qiisqwww/HeadmanBot pull request #29
Opened 2024-06-20 14:22 UTC by qiisqwww

## Обновление панели с расписанием

**Была обновлена панель расписания.** Теперь студенту доступно расписание на _3 следующие недели_ (начиная с текущей). 

![image](https://github.com/qiisqwww/HeadmanBot/assets/146729208/346698a3-fa4d-470b-b557-03dcc09e2dba)

![изображение_2024-06-20_171900817](https://github.com/qiisqwww/HeadmanBot/assets/146729208/853addd3-0f54-4288-9a38-7307a9a7187b)

На **первом** изображении представлено меню, которое видит пользователь при вводе команды _"Узнать расписание"_.
Он может получить расписание на текущий день, либо открыть какой-то конкретный день с помощью навигации по неделям.

На **втором** изображении представлена навигация пользователем по неделе. Он может выбрать любой день и посмотреть расписание на него. Кнопка _"Вернуться назад"_ вернет пользователя в предыдущее меню.

2024-06-22 07:07 UTC, NeoTheBestDeveloper requested changes
В целом хорошо, но нужно пару правко сделать

2024-06-22 07:07 UTC, NeoTheBestDeveloper commented on src/bot/show_schedule/callbacks/show_schedule_day_callback.py
> +            "сегодня" if chosen_day.__str__() == date.today().__str__() else chosen_day.__str__(),
1. Ты можешь просто обернуть объект в str(), а не вызывать его dunder метод напрямую
2. Попробуй не приводить даты к строке, они и так будут замечательно сравниваться

2024-06-22 07:07 UTC, NeoTheBestDeveloper commented on src/bot/show_schedule/resources/inline_buttons.py
> +            text=get_short_name_of_day(i) + " | " + week_runner.__str__(),
Не стоит вызывать dunder метод напрямую

2024-06-22 07:07 UTC, NeoTheBestDeveloper commented on src/bot/common/command_filter/callback_data.py
Я так и не понял, зачем нужен этот класс

2024-06-23 11:18 UTC, qiisqwww commented
Исправлены ошибки, на которые было указано в code review.
Добавлена возможность получения расписания вводом конкретной даты вручную.

На первой картинке изображен обновленный вариант меню. 
![image](https://github.com/qiisqwww/HeadmanBot/assets/146729208/f468b5bb-2989-4dc1-a24a-2a20d21faa47)

На второй картинке изображен процесс получения расписания на какую-либо дату.
![image](https://github.com/qiisqwww/HeadmanBot/assets/146729208/a84dbb71-312b-4275-b748-445a6921bb8e)

2024-06-26 16:21 UTC, NeoTheBestDeveloper approved these changes

2024-06-26 16:21 UTC, merged